apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: task
type: Opaque
data:
  postgres-user: Ym9va3N0b3JldXNlcg==
  postgres-password: Y3JlZHJhaWxzMTIz
  postgres-db: Y3JlZHJhaWxzMFlj
