apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: task
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer # Change this to ClusterIP or NodePort if needed
